apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: youngest-tern-go 
  janus-idp.io/tekton: youngest-tern-go
  backstage.io/kubernetes-id: youngest-tern-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: youngest-tern-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  