apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: youngest-tern-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: youngest-tern-go 
  name: youngest-tern-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: youngest-tern-go 
